### ISSUE TITLE
Multiple optional routes result in unexpected behavior

### ISSUE THREAD

**Issue by laposheureux** [joeldev/JLRoutes#75]
`:thing/path/:anotherthing(/new)(/anotherpath/:athirdthing)`

Results in the unmatched handler being called for:

`http://url.com/path/12345/anotherpath/54321`

This path should be handled in the case where (/new) is optionally omitted, but it is not.

Defining the route as two separate routes manually including and not including `/new` in the path results in expected behavior.

**Comment by joeldev** [comment]
In this case, it's because `url.com` is not considered part of the route. So `:thing/path` is already a mismatch for the pattern (which starts with `path/12345`). That route pattern will never be a match for that URL.

However, there does seem to be a bug with optionals that are followed by other optionals. I'm looking into implementing a fix for that and will keep this issue open for now.
