### ISSUE TITLE
Can not match the following situation

### ISSUE THREAD

**Issue by DeanCarter** [joeldev/JLRoutes#95]
I registered route "/Channel/:channelId" and "/Channel/Live/:sid/:ssid",  When I opened URI for the "myapp://Channel/Live?sid=12345&ssid=87654", but the mathing result is route "/Channel/:channelId", but not “/Channel/Live/:sid/:ssid”

**Comment by joeldev** [comment]
This is behaving correctly.

If you want to match the URL `myapp://Channel/Live?sid=12345&ssid=87654` with a route, you'd need to use a route for `/Channel/Live`. The `sid` and `ssid` parameters will be passed in the parameter dictionary. It's matching `/Channel/:channelId` instead because `/Channel/Live` is a valid match for that route, with a `channelId` of `"Live"`.

To match a route with pattern `/Channel/Live/:sid/:ssid`, the URL would need to be like this instead: `myapp://Channel/Live/12345/87654` (same `sid` and `ssid` as above).
